# Generated by Django 5.1.6 on 2025-03-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='Comunidad.administrador')),
                ('usuarios', models.ManyToManyField(related_name='comunidades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
