# Generated by Django 5.1.6 on 2025-03-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0002_alter_administrador_user_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CategoriaTarea',
                'verbose_name_plural': 'CategoriasTareas',
            },
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.categoriatarea'),
        ),
    ]
