# Generated by Django 5.1.6 on 2025-03-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0003_categoriatarea_alter_publicacion_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
