# Generated by Django 5.1.6 on 2025-03-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0004_rename_titulo_publicacion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='nombre',
            new_name='categoria',
        ),
    ]
