# Generated by Django 5.1.6 on 2025-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0007_solicitudunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudunion',
            name='visto_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
